"""empty message

Revision ID: c1f6492fd2f5
Revises: e244269ef835
Create Date: 2021-03-16 15:19:18.747514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f6492fd2f5'
down_revision = 'e244269ef835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Article', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Article', 'location')
    # ### end Alembic commands ###
