"""empty message

Revision ID: f0763db5c1d7
Revises: f1b61f438afc
Create Date: 2021-04-08 16:26:16.623032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0763db5c1d7'
down_revision = 'f1b61f438afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'views')
    # ### end Alembic commands ###
